// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulwslahrohfvnlkmsfiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsd3NsYWhyb2hmdm5sa21zZml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDkzMzIsImV4cCI6MjA3MjEyNTMzMn0.CvPPMP5uwwLf2jxNx1YzzYMv6MqlJ0w92zgn7ZwmEfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});